# Paleta de colores del sistema DigiCable

# === PALETA PRINCIPAL ===
AZUL_NOCHE = "#031D44"
AZUL_MARINO = "#084887"
AZUL_CERULEO = "#219EBC"
AZUL_CIELO = "#8ECAE6"
BLANCO_CALIDO = "#F7F5FB"
AMARILLO_AMBAR = "#FFB703"
NARANJA_INTENSO = "#FB8500"
GRIS_AZULADO = "#2D3748"
NARANJA_SELECCION = "#F58A07"

# === HOVER VARIANTS ===
HOVER_CERULEO = "#1976A1"
HOVER_MARINO = "#031D44"
HOVER_AMBAR = "#E6A500"
HOVER_NARANJA_SEL = "#D67A00"
HOVER_NARANJA_INT = "#E67600"
HOVER_FILTRO_DISP = "#126782"
HOVER_MOV_ASIG = "#6BB8D9"
HOVER_MOV_CANCEL = "#C26800"
HOVER_EXPORT = "#E69545"

# === PRODUCT STATUS PILLS ===
DISPONIBLE_BG = "#DFF1E6"
DISPONIBLE_FG = "#2F8A55"
NO_DISPONIBLE_BG = "#FDECC8"
NO_DISPONIBLE_FG = "#B45309"
INACTIVO_BG = "#FDE2E0"
INACTIVO_FG = "#B42318"

# === STOCK INDICATORS ===
STOCK_DISP_BG = DISPONIBLE_BG
STOCK_DISP_FG = DISPONIBLE_FG
STOCK_BAJO_BG = NO_DISPONIBLE_BG
STOCK_BAJO_FG = NO_DISPONIBLE_FG
STOCK_AGOTADO_BG = INACTIVO_BG
STOCK_AGOTADO_FG = INACTIVO_FG

# === DASHBOARD MOVEMENT TYPE COLORS ===
MOV_ENTRADA_BG = "#D4EDDA"
MOV_ENTRADA_FG = "#155724"
MOV_SALIDA_BG = "#F8D7DA"
MOV_SALIDA_FG = "#721C24"
MOV_ASIGNACION_BG = "#D1ECF1"
MOV_ASIGNACION_FG = "#0C5460"
MOV_DEVOLUCION_BG = "#FFF3CD"
MOV_DEVOLUCION_FG = "#856404"
MOV_DEFAULT_BG = "#F8F9FA"
MOV_DEFAULT_FG = "#6C757D"

# === TABLE / LIST SURFACES ===
BLANCO = "#FFFFFF"
FONDO_TABLA = BLANCO
FONDO_SCROLL = "#EFEFEF"
FONDO_ROW_PAR = "#EAF4FB"
FONDO_ROW_IMPAR = "#F0F7FF"
FONDO_EXPANDIDO = "#FAFBFD"
FONDO_SUBHEADER = "#E8F1F8"
FONDO_BADGE = "#EEF0F3"
FONDO_BTN_PIE = "#E8ECF0"
FONDO_MULTISELECT = "#F3F4F6"
FONDO_MULTI_QTY = "#F0F4F8"

# === TEXT ===
TEXTO_SECUNDARIO = "#6B7280"
TEXTO_PLACEHOLDER = "#9CA3AF"
TEXTO_PLACEHOLDER_LOGIN = "#A0AEC0"
TEXTO_MODELO = "#1B1F24"
TEXTO_DASH_LABEL = "#2C3E50"
TEXTO_DASH_SEC = "#6C757D"
TEXTO_DASH_HINT = "#CCCCCC"
TEXTO_MOV_FIELD = "#023047"

# === INTERACTION ===
SELECCION_BG = "#FFF4E6"
HOVER_FILA_BG = "#F5F7FB"
CHEVRON_HOVER = "#D4E6F1"

# === BUTTON FILTERS ===
FILTRO_TODOS_FG = AZUL_MARINO
FILTRO_TODOS_HOVER = AZUL_NOCHE
FILTRO_DISP_FG = AZUL_CERULEO
FILTRO_DISP_HOVER = HOVER_FILTRO_DISP
FILTRO_NO_DISP_FG = AMARILLO_AMBAR
FILTRO_NO_DISP_HOVER = HOVER_AMBAR
FILTRO_ENTRADA_FG = AZUL_CERULEO
FILTRO_ENTRADA_HOVER = HOVER_FILTRO_DISP
FILTRO_SALIDA_FG = NARANJA_SELECCION
FILTRO_SALIDA_HOVER = HOVER_NARANJA_SEL
FILTRO_DEVOLUCION_FG = AMARILLO_AMBAR
FILTRO_DEVOLUCION_HOVER = HOVER_AMBAR
FILTRO_ASIGNACION_FG = AZUL_CIELO
FILTRO_ASIGNACION_HOVER = HOVER_MOV_ASIG

# === SIDEBAR ===
SIDEBAR_BG = AZUL_NOCHE
SIDEBAR_TEXT = BLANCO_CALIDO
SIDEBAR_HOVER = "#063A69"
SIDEBAR_ACTIVE = NARANJA_SELECCION
SIDEBAR_SUBTITLE = AZUL_CIELO
SIDEBAR_DIVIDER = AZUL_MARINO

# === DASHBOARD ===
DASHBOARD_BORDER = NARANJA_SELECCION
DASHBOARD_CARD_BG = BLANCO
DASHBOARD_CARD_BORDER = BLANCO
DASHBOARD_BG = "#F8F9FA"
DASHBOARD_CARD_BORDER_SEC = "#D5D8DB"

# === WAREHOUSE BAR ===
WH_BAR_BG = BLANCO_CALIDO
WH_SEG_FG = "#E2EFF8"
WH_SEG_SELECTED = AZUL_CERULEO
WH_SEG_HOVER = "#C5DFF0"
WH_DIVIDER = AZUL_CIELO

# === BORDERS ===
BORDE_TABLA = AZUL_MARINO
BORDE_CAMPO = AZUL_MARINO
BORDE_ALERTA = NARANJA_INTENSO
BORDE_GUARDAR = AZUL_NOCHE

# === GENERIC ===
PELIGRO_BG = NARANJA_INTENSO
PELIGRO_HOVER = HOVER_NARANJA_INT
CANCELAR_BG = "#A0AEC0"
CANCELAR_HOVER = "#718096"
SUCCESS_BG = AZUL_CERULEO
SUCCESS_HOVER = HOVER_CERULEO
DIALOG_HEADER = AZUL_NOCHE
